// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_JapineseMecabDelM.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mecabInfo;

public final class _JapineseMecabDelM extends Ice._ObjectDelM implements _JapineseMecabDel
{
    public java.util.Map<String, String>
    getPictureStr(String context, String language, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               MecabException
    {
        IceInternal.Outgoing __og = __handler.getOutgoing("getPictureStr", Ice.OperationMode.Normal, __ctx);
        try
        {
            try
            {
                IceInternal.BasicStream __os = __og.os();
                __os.writeString(context);
                __os.writeString(language);
            }
            catch(Ice.LocalException __ex)
            {
                __og.abort(__ex);
            }
            boolean __ok = __og.invoke();
            try
            {
                if(!__ok)
                {
                    try
                    {
                        __og.throwUserException();
                    }
                    catch(MecabException __ex)
                    {
                        throw __ex;
                    }
                    catch(Ice.UserException __ex)
                    {
                        throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                    }
                }
                IceInternal.BasicStream __is = __og.is();
                __is.startReadEncaps();
                java.util.Map<String, String> __ret;
                __ret = CustomMapHelper.read(__is);
                __is.endReadEncaps();
                return __ret;
            }
            catch(Ice.LocalException __ex)
            {
                throw new IceInternal.LocalExceptionWrapper(__ex, false);
            }
        }
        finally
        {
            __handler.reclaimOutgoing(__og);
        }
    }
}
