// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_JapineseMecabDelD.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mecabInfo;

public final class _JapineseMecabDelD extends Ice._ObjectDelD implements _JapineseMecabDel
{
    public java.util.Map<String, String>
    getPictureStr(final String context, final String language, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               MecabException
    {
        final Ice.Current __current = new Ice.Current();
        __initCurrent(__current, "getPictureStr", Ice.OperationMode.Normal, __ctx);
        final CustomMapHolder __result = new CustomMapHolder();
        IceInternal.Direct __direct = null;
        try
        {
            __direct = new IceInternal.Direct(__current)
            {
                public Ice.DispatchStatus run(Ice.Object __obj)
                {
                    JapineseMecab __servant = null;
                    try
                    {
                        __servant = (JapineseMecab)__obj;
                    }
                    catch(ClassCastException __ex)
                    {
                        throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
                    }
                    try
                    {
                        __result.value = __servant.getPictureStr(context, language, __current);
                        return Ice.DispatchStatus.DispatchOK;
                    }
                    catch(Ice.UserException __ex)
                    {
                        setUserException(__ex);
                        return Ice.DispatchStatus.DispatchUserException;
                    }
                }
            };
            try
            {
                Ice.DispatchStatus __status = __direct.servant().__collocDispatch(__direct);
                if(__status == Ice.DispatchStatus.DispatchUserException)
                {
                    __direct.throwUserException();
                }
                assert __status == Ice.DispatchStatus.DispatchOK;
                return __result.value;
            }
            finally
            {
                __direct.destroy();
            }
        }
        catch(MecabException __ex)
        {
            throw __ex;
        }
        catch(Ice.SystemException __ex)
        {
            throw __ex;
        }
        catch(Throwable __ex)
        {
            IceInternal.LocalExceptionWrapper.throwWrapper(__ex);
        }
        return __result.value;
    }
}
