// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_JapineseMecabOperationsNC.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mecabInfo;

public interface _JapineseMecabOperationsNC
{
    /**
     * 对日文进行mecab分词
     **/
    java.util.Map<String, String> getPictureStr(String context, String language)
        throws MecabException;
}
