// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `JapineseMecabPrx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mecabInfo;

public interface JapineseMecabPrx extends Ice.ObjectPrx
{
    /**
     * 对日文进行mecab分词
     **/
    public java.util.Map<String, String> getPictureStr(String context, String language)
        throws MecabException;

    /**
     * 对日文进行mecab分词
     * @param __ctx The Context map to send with the invocation.
     **/
    public java.util.Map<String, String> getPictureStr(String context, String language, java.util.Map<String, String> __ctx)
        throws MecabException;

    /**
     * 对日文进行mecab分词
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language);

    /**
     * 对日文进行mecab分词
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language, java.util.Map<String, String> __ctx);

    /**
     * 对日文进行mecab分词
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language, Ice.Callback __cb);

    /**
     * 对日文进行mecab分词
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 对日文进行mecab分词
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language, Callback_JapineseMecab_getPictureStr __cb);

    /**
     * 对日文进行mecab分词
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language, java.util.Map<String, String> __ctx, Callback_JapineseMecab_getPictureStr __cb);

    /**
     * 对日文进行mecab分词
     * @param __result The asynchronous result object.
     **/
    public java.util.Map<String, String> end_getPictureStr(Ice.AsyncResult __result)
        throws MecabException;
}
