// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `JapineseMecabPrxHelper.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mecabInfo;

public final class JapineseMecabPrxHelper extends Ice.ObjectPrxHelperBase implements JapineseMecabPrx
{
    /**
     * 对日文进行mecab分词
     **/
    public java.util.Map<String, String>
    getPictureStr(String context, String language)
        throws MecabException
    {
        return getPictureStr(context, language, null, false);
    }

    /**
     * 对日文进行mecab分词
     * @param __ctx The Context map to send with the invocation.
     **/
    public java.util.Map<String, String>
    getPictureStr(String context, String language, java.util.Map<String, String> __ctx)
        throws MecabException
    {
        return getPictureStr(context, language, __ctx, true);
    }

    private java.util.Map<String, String>
    getPictureStr(String context, String language, java.util.Map<String, String> __ctx, boolean __explicitCtx)
        throws MecabException
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        int __cnt = 0;
        while(true)
        {
            Ice._ObjectDel __delBase = null;
            try
            {
                __checkTwowayOnly("getPictureStr");
                __delBase = __getDelegate(false);
                _JapineseMecabDel __del = (_JapineseMecabDel)__delBase;
                return __del.getPictureStr(context, language, __ctx);
            }
            catch(IceInternal.LocalExceptionWrapper __ex)
            {
                __handleExceptionWrapper(__delBase, __ex);
            }
            catch(Ice.LocalException __ex)
            {
                __cnt = __handleException(__delBase, __ex, null, __cnt);
            }
        }
    }

    private static final String __getPictureStr_name = "getPictureStr";

    /**
     * 对日文进行mecab分词
     * @param __cb The callback object for the operation.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language)
    {
        return begin_getPictureStr(context, language, null, false, null);
    }

    /**
     * 对日文进行mecab分词
     * @param __cb The callback object for the operation.
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language, java.util.Map<String, String> __ctx)
    {
        return begin_getPictureStr(context, language, __ctx, true, null);
    }

    /**
     * 对日文进行mecab分词
     * @param __cb The callback object for the operation.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language, Ice.Callback __cb)
    {
        return begin_getPictureStr(context, language, null, false, __cb);
    }

    /**
     * 对日文进行mecab分词
     * @param __cb The callback object for the operation.
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getPictureStr(context, language, __ctx, true, __cb);
    }

    /**
     * 对日文进行mecab分词
     * @param __cb The callback object for the operation.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language, Callback_JapineseMecab_getPictureStr __cb)
    {
        return begin_getPictureStr(context, language, null, false, __cb);
    }

    /**
     * 对日文进行mecab分词
     * @param __cb The callback object for the operation.
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_getPictureStr(String context, String language, java.util.Map<String, String> __ctx, Callback_JapineseMecab_getPictureStr __cb)
    {
        return begin_getPictureStr(context, language, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_getPictureStr(String context, String language, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getPictureStr_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getPictureStr_name, __cb);
        try
        {
            __result.__prepare(__getPictureStr_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__os();
            __os.writeString(context);
            __os.writeString(language);
            __os.endWriteEncaps();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    /**
     * ice_response indicates that
     * the operation completed successfully.
     **/
    public java.util.Map<String, String> end_getPictureStr(Ice.AsyncResult __result)
        throws MecabException
    {
        Ice.AsyncResult.__check(__result, this, __getPictureStr_name);
        if(!__result.__wait())
        {
            try
            {
                __result.__throwUserException();
            }
            catch(MecabException __ex)
            {
                throw __ex;
            }
            catch(Ice.UserException __ex)
            {
                throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
            }
        }
        java.util.Map<String, String> __ret;
        IceInternal.BasicStream __is = __result.__is();
        __is.startReadEncaps();
        __ret = CustomMapHelper.read(__is);
        __is.endReadEncaps();
        return __ret;
    }

    public static JapineseMecabPrx
    checkedCast(Ice.ObjectPrx __obj)
    {
        JapineseMecabPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (JapineseMecabPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    JapineseMecabPrxHelper __h = new JapineseMecabPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static JapineseMecabPrx
    checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        JapineseMecabPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (JapineseMecabPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    JapineseMecabPrxHelper __h = new JapineseMecabPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static JapineseMecabPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        JapineseMecabPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    JapineseMecabPrxHelper __h = new JapineseMecabPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static JapineseMecabPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        JapineseMecabPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    JapineseMecabPrxHelper __h = new JapineseMecabPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static JapineseMecabPrx
    uncheckedCast(Ice.ObjectPrx __obj)
    {
        JapineseMecabPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (JapineseMecabPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                JapineseMecabPrxHelper __h = new JapineseMecabPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static JapineseMecabPrx
    uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        JapineseMecabPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            JapineseMecabPrxHelper __h = new JapineseMecabPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::mecabInfo::JapineseMecab"
    };

    public static String
    ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM
    __createDelegateM()
    {
        return new _JapineseMecabDelM();
    }

    protected Ice._ObjectDelD
    __createDelegateD()
    {
        return new _JapineseMecabDelD();
    }

    public static void
    __write(IceInternal.BasicStream __os, JapineseMecabPrx v)
    {
        __os.writeProxy(v);
    }

    public static JapineseMecabPrx
    __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            JapineseMecabPrxHelper result = new JapineseMecabPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }
}
